import { useState, useEffect } from 'react';
import { HiX, HiCheckCircle, HiCreditCard, HiLibrary, HiDeviceMobile } from 'react-icons/hi';
import { motion, AnimatePresence } from 'framer-motion';

export default function PaymentSimulatorModal({ isOpen, onClose, onPaymentSuccess, orderData, bookTitle }) {
    const [step, setStep] = useState('methods'); // methods, processing, success
    const [selectedMethod, setSelectedMethod] = useState(null);
    const [loading, setLoading] = useState(false);

    const methods = [
        { id: 'upi', name: 'UPI (GPay, PhonePe, UPI ID)', icon: <HiDeviceMobile className="text-xl" />, color: '#5f27cd' },
        { id: 'card', name: 'Credit/Debit Card', icon: <HiCreditCard className="text-xl" />, color: '#341f97' },
        { id: 'netbanking', name: 'Netbanking', icon: <HiLibrary className="text-xl" />, color: '#1dd1a1' },
        { id: 'wallet', name: 'Wallet Balance', icon: <div className="text-xs font-bold">W</div>, color: '#ff9f43' }
    ];

    const handlePay = () => {
        if (!selectedMethod) return;
        setStep('processing');

        // Simulate gateway delay
        setTimeout(() => {
            // Generate simulated response like Razorpay
            const paymentId = 'sim_pay_' + Math.random().toString(36).substr(2, 9);
            // Signature is usually generated by backend for verification, 
            // but in this simulation we can just mock it or call a simulation endpoint

            onPaymentSuccess({
                razorpay_order_id: orderData.razorpay_order_id,
                razorpay_payment_id: paymentId,
                razorpay_signature: 'sim_sig_' + Math.random().toString(36).substr(2, 20)
            });
            setStep('success');
        }, 2000);
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
            <motion.div
                initial={{ scale: 0.9, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                exit={{ scale: 0.9, opacity: 0 }}
                className="w-full max-w-md bg-[#1a1a1a] border border-white/10 rounded-2xl overflow-hidden shadow-2xl"
            >
                {/* Header */}
                <div className="p-6 border-b border-white/5 flex justify-between items-center bg-gradient-to-r from-blue-600/10 to-purple-600/10">
                    <div>
                        <h2 className="text-lg font-bold text-white">Payment Gateway</h2>
                        <p className="text-xs text-slate-400">Merchant: Digital BookShop</p>
                    </div>
                    <button onClick={onClose} className="p-2 hover:bg-white/5 rounded-full text-slate-400 transition-colors">
                        <HiX />
                    </button>
                </div>

                <div className="p-6">
                    <AnimatePresence mode="wait">
                        {step === 'methods' && (
                            <motion.div
                                key="methods"
                                initial={{ x: 20, opacity: 0 }}
                                animate={{ x: 0, opacity: 1 }}
                                exit={{ x: -20, opacity: 0 }}
                            >
                                <div className="mb-6 p-4 bg-white/5 rounded-xl border border-white/5">
                                    <div className="text-xs text-slate-400 mb-1">PAYING FOR</div>
                                    <div className="text-sm font-semibold text-white truncate">{bookTitle}</div>
                                    <div className="mt-2 text-2xl font-bold text-blue-400">₹{orderData.amount}</div>
                                </div>

                                <div className="space-y-3">
                                    <p className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Select Payment Method</p>
                                    {methods.map((method) => (
                                        <button
                                            key={method.id}
                                            onClick={() => setSelectedMethod(method.id)}
                                            className={`w-full flex items-center gap-4 p-4 rounded-xl border transition-all ${selectedMethod === method.id
                                                    ? 'bg-blue-600/10 border-blue-500 text-white'
                                                    : 'bg-white/5 border-white/5 text-slate-300 hover:bg-white/10'
                                                }`}
                                        >
                                            <div className="p-2 rounded-lg" style={{ background: method.color + '20', color: method.color }}>
                                                {method.icon}
                                            </div>
                                            <span className="flex-1 text-left font-medium">{method.name}</span>
                                            {selectedMethod === method.id && <div className="w-2 h-2 rounded-full bg-blue-500 shadow-[0_0_10px_#3b82f6]" />}
                                        </button>
                                    ))}
                                </div>

                                <button
                                    disabled={!selectedMethod}
                                    onClick={handlePay}
                                    className={`w-full mt-8 py-4 rounded-xl font-bold flex items-center justify-center gap-2 transition-all ${selectedMethod
                                            ? 'bg-blue-600 hover:bg-blue-500 text-white shadow-lg shadow-blue-600/20'
                                            : 'bg-white/5 text-slate-500 cursor-not-allowed'
                                        }`}
                                >
                                    Pay Now ₹{orderData.amount}
                                </button>
                                <p className="text-[10px] text-center text-slate-500 mt-4">
                                    Secured by Antigravity Payment Simulation. No real money will be deducted.
                                </p>
                            </motion.div>
                        )}

                        {step === 'processing' && (
                            <motion.div
                                key="processing"
                                initial={{ opacity: 0 }}
                                animate={{ opacity: 1 }}
                                className="py-12 flex flex-col items-center justify-center text-center"
                            >
                                <div className="relative w-20 h-20 mb-6">
                                    <div className="absolute inset-0 border-4 border-blue-500/20 rounded-full"></div>
                                    <div className="absolute inset-0 border-4 border-t-blue-500 rounded-full animate-spin"></div>
                                </div>
                                <h3 className="text-xl font-bold text-white mb-2">Simulating Payment...</h3>
                                <p className="text-slate-400 max-w-[200px]">Connecting to simulated bank servers</p>
                            </motion.div>
                        )}

                        {step === 'success' && (
                            <motion.div
                                key="success"
                                initial={{ scale: 0.8, opacity: 0 }}
                                animate={{ scale: 1, opacity: 1 }}
                                className="py-12 flex flex-col items-center justify-center text-center"
                            >
                                <div className="w-20 h-20 bg-green-500/20 text-green-500 rounded-full flex items-center justify-center mb-6">
                                    <HiCheckCircle className="text-6xl" />
                                </div>
                                <h3 className="text-2xl font-bold text-white mb-2">Payment Successful!</h3>
                                <p className="text-slate-400 mb-8">Your transaction has been processed</p>
                                <button
                                    onClick={onClose}
                                    className="w-full py-3 bg-green-600 hover:bg-green-500 text-white font-bold rounded-xl transition-colors"
                                >
                                    Continue
                                </button>
                            </motion.div>
                        )}
                    </AnimatePresence>
                </div>
            </motion.div>
        </div>
    );
}
