import { useState, useEffect } from 'react';
import { HiX, HiCheckCircle, HiCreditCard, HiLibrary, HiDeviceMobile } from 'react-icons/hi';
import { motion, AnimatePresence } from 'framer-motion';
import { HiOutlineLockClosed } from 'react-icons/hi';
import { userService } from '../services';
import toast from 'react-hot-toast';

export default function PaymentSimulatorModal({ isOpen, onClose, onPaymentSuccess, orderData, bookTitle }) {
    const [step, setStep] = useState('methods'); // methods, processing, success
    const [selectedMethod, setSelectedMethod] = useState(null);
    const [paymentPassword, setPaymentPassword] = useState('');
    const [showForgot, setShowForgot] = useState(false);
    const [paymentError, setPaymentError] = useState('');
    const [otp, setOtp] = useState('');
    const [resetPassword, setResetPassword] = useState('');
    const [resetConfirm, setResetConfirm] = useState('');
    const [isSendingOtp, setIsSendingOtp] = useState(false);
    const [isResetting, setIsResetting] = useState(false);

    useEffect(() => {
        if (!isOpen) {
            setStep('methods');
            setSelectedMethod(null);
            setPaymentPassword('');
            setShowForgot(false);
            setPaymentError('');
            setOtp('');
            setResetPassword('');
            setResetConfirm('');
        }
    }, [isOpen]);

    const methods = [
        { id: 'upi', name: 'UPI (GPay, PhonePe, UPI ID)', icon: <HiDeviceMobile className="text-xl" />, color: '#5f27cd' },
        { id: 'card', name: 'Credit/Debit Card', icon: <HiCreditCard className="text-xl" />, color: '#341f97' },
        { id: 'netbanking', name: 'Netbanking', icon: <HiLibrary className="text-xl" />, color: '#1dd1a1' },
        { id: 'wallet', name: 'Wallet Balance', icon: <div className="text-xs font-bold">W</div>, color: '#ff9f43' }
    ];

    const handlePay = () => {
        if (!selectedMethod) return;
        if (!paymentPassword) return;
        setPaymentError('');
        setStep('processing');

        // Simulate gateway delay
        setTimeout(async () => {
            // Generate simulated response like Razorpay
            const paymentId = 'sim_pay_' + Math.random().toString(36).substr(2, 9);
            // Signature is usually generated by backend for verification, 
            // but in this simulation we can just mock it or call a simulation endpoint

            try {
                const result = await onPaymentSuccess({
                    razorpay_order_id: orderData.razorpay_order_id,
                    razorpay_payment_id: paymentId,
                    razorpay_signature: 'sim_sig_' + Math.random().toString(36).substr(2, 20),
                    password: paymentPassword,
                });
                if (result?.ok === true) {
                    setStep('success');
                } else {
                    setStep('methods');
                    setPaymentError(result?.message || 'Payment failed. Please try again.');
                }
            } catch (err) {
                setStep('methods');
                setPaymentError('Payment failed. Please try again.');
            }
        }, 2000);
    };

    const handleSendOtp = async () => {
        setIsSendingOtp(true);
        try {
            await userService.requestTransactionPasswordReset();
            toast.success('OTP sent to notifications');
        } catch (err) {
            toast.error(err.response?.data?.message || 'Failed to send OTP');
        } finally {
            setIsSendingOtp(false);
        }
    };

    const handleResetPassword = async () => {
        if (!otp || !resetPassword || resetPassword.length < 4) {
            toast.error('Enter OTP and a new password (min 4 characters)');
            return;
        }
        if (resetPassword !== resetConfirm) {
            toast.error('Passwords do not match');
            return;
        }
        setIsResetting(true);
        try {
            await userService.resetTransactionPassword({ otp, new_password: resetPassword });
            setOtp('');
            setResetPassword('');
            setResetConfirm('');
            setPaymentPassword('');
            setShowForgot(false);
            toast.success('Password reset. Use your new password to continue.');
        } catch (err) {
            toast.error(err.response?.data?.message || 'Failed to reset password');
        } finally {
            setIsResetting(false);
        }
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
            <motion.div
                initial={{ scale: 0.9, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                exit={{ scale: 0.9, opacity: 0 }}
                className="w-full max-w-md bg-[#111827] border border-white/20 rounded-2xl overflow-hidden shadow-2xl"
                style={{ color: '#e2e8f0' }}
            >
                {/* Header */}
                <div className="p-6 border-b border-white/15 flex justify-between items-center bg-gradient-to-r from-blue-600/40 to-purple-600/40">
                    <div>
                        <h2 className="text-lg font-bold" style={{ color: '#f8fafc' }}>Payment Gateway</h2>
                        <p className="text-xs" style={{ color: '#e2e8f0' }}>Merchant: BOoCArT</p>
                    </div>
                    <button onClick={onClose} className="p-2 hover:bg-white/15 rounded-full transition-colors" style={{ color: '#f8fafc' }}>
                        <HiX />
                    </button>
                </div>

                <div className="p-6">
                    <AnimatePresence mode="wait">
                        {step === 'methods' && (
                            <motion.div
                                key="methods"
                                initial={{ x: 20, opacity: 0 }}
                                animate={{ x: 0, opacity: 1 }}
                                exit={{ x: -20, opacity: 0 }}
                            >
                                <div className="mb-6 p-4 rounded-xl border border-white/20" style={{ background: 'rgba(255,255,255,0.14)' }}>
                                    <div className="text-xs mb-1" style={{ color: '#e2e8f0' }}>PAYING FOR</div>
                                    <div className="text-sm font-semibold truncate" style={{ color: '#f8fafc' }}>{bookTitle}</div>
                                    <div className="mt-2 text-2xl font-bold text-blue-400">₹{orderData.amount}</div>
                                </div>

                                <div className="space-y-3">
                                    <p className="text-xs font-semibold uppercase tracking-wider" style={{ color: '#e2e8f0' }}>Select Payment Method</p>
                                    {methods.map((method) => (
                                        <button
                                            key={method.id}
                                            onClick={() => setSelectedMethod(method.id)}
                                            className={`w-full flex items-center gap-4 p-4 rounded-xl border transition-all ${selectedMethod === method.id
                                                    ? 'bg-blue-600/10 border-blue-500 text-white'
                                                    : 'bg-white/20 border-white/20 hover:bg-white/25'
                                                }`}
                                            style={{ color: '#f8fafc' }}
                                        >
                                            <div className="p-2 rounded-lg" style={{ background: method.color + '20', color: method.color }}>
                                                {method.icon}
                                            </div>
                                            <span className="flex-1 text-left font-medium">{method.name}</span>
                                            {selectedMethod === method.id && <div className="w-2 h-2 rounded-full bg-blue-500 shadow-[0_0_10px_#3b82f6]" />}
                                        </button>
                                    ))}
                                </div>

                                {selectedMethod && (
                                    <div className="mt-6">
                                        <label className="text-xs font-semibold uppercase tracking-wider flex items-center gap-2 mb-2" style={{ color: '#e2e8f0' }}>
                                            <HiOutlineLockClosed className="text-sm" />
                                            Transaction password
                                        </label>
                                        <div className="relative">
                                            <input
                                                type="password"
                                                value={paymentPassword}
                                                onChange={(e) => setPaymentPassword(e.target.value)}
                                                placeholder="Enter transaction password"
                                                className="w-full bg-white/5 border border-white/5 rounded-xl py-3 pl-4 pr-4 text-white placeholder:text-slate-400 focus:outline-none focus:border-blue-500 transition-colors"
                                                style={{ color: '#e2e8f0' }}
                                            />
                                        </div>
                                        {!paymentPassword && (
                                            <p className="text-[11px] text-red-500 mt-2">Password required to proceed.</p>
                                        )}
                                        {paymentError && (
                                            <p className="text-[11px] text-red-500 mt-2">{paymentError}</p>
                                        )}
                                        <div className="mt-3 flex items-center justify-between">
                                            <p className="text-[11px]" style={{ color: '#e2e8f0' }}>Required for wallet payments and orders.</p>
                                            <button
                                                type="button"
                                                onClick={() => setShowForgot((prev) => !prev)}
                                                className="text-[11px] hover:opacity-90"
                                                style={{ color: '#93c5fd' }}
                                            >
                                                {showForgot ? 'Back to payment' : 'Forgot password?'}
                                            </button>
                                        </div>

                                        {showForgot && (
                                            <div className="mt-4 rounded-xl border border-white/20 p-4 space-y-3" style={{ background: 'rgba(255,255,255,0.16)' }}>
                                                <div className="flex items-center justify-between">
                                                    <span className="text-[10px] uppercase tracking-wider" style={{ color: '#e2e8f0' }}>Reset with OTP</span>
                                                    <button
                                                        type="button"
                                                        onClick={handleSendOtp}
                                                        disabled={isSendingOtp}
                                                        className="text-[11px] hover:opacity-90"
                                                        style={{ color: '#93c5fd' }}
                                                    >
                                                        {isSendingOtp ? 'Sending...' : 'Send OTP'}
                                                    </button>
                                                </div>
                                                <input
                                                    type="text"
                                                    value={otp}
                                                    onChange={(e) => setOtp(e.target.value)}
                                                    className="w-full bg-white/5 border border-white/10 rounded-xl py-2.5 px-3 text-white placeholder:text-slate-600"
                                                    placeholder="Enter OTP"
                                                />
                                                <input
                                                    type="password"
                                                    value={resetPassword}
                                                    onChange={(e) => setResetPassword(e.target.value)}
                                                    className="w-full bg-white/5 border border-white/10 rounded-xl py-2.5 px-3 text-white placeholder:text-slate-600"
                                                    placeholder="New password"
                                                />
                                                <input
                                                    type="password"
                                                    value={resetConfirm}
                                                    onChange={(e) => setResetConfirm(e.target.value)}
                                                    className="w-full bg-white/5 border border-white/10 rounded-xl py-2.5 px-3 text-white placeholder:text-slate-600"
                                                    placeholder="Confirm new password"
                                                />
                                                <button
                                                    type="button"
                                                    onClick={handleResetPassword}
                                                    disabled={isResetting}
                                                    className="w-full btn-primary py-2 text-xs"
                                                >
                                                    {isResetting ? 'Resetting...' : 'Reset Password'}
                                                </button>
                                                <p className="text-[10px]" style={{ color: '#e2e8f0' }}>OTP will arrive in Notifications.</p>
                                            </div>
                                        )}
                                    </div>
                                )}

                                <button
                                    disabled={!selectedMethod || !paymentPassword}
                                    onClick={handlePay}
                                    className={`w-full mt-8 py-4 rounded-xl font-bold flex items-center justify-center gap-2 transition-all ${selectedMethod
                                            ? 'bg-blue-600 hover:bg-blue-500 text-white shadow-lg shadow-blue-600/20'
                                            : 'cursor-not-allowed border border-white/20'
                                        }`}
                                    style={!selectedMethod ? { background: 'rgba(255,255,255,0.2)', color: '#f8fafc' } : {}}
                                >
                                    Pay Now ₹{orderData.amount}
                                </button>
                                <p className="text-[10px] text-center mt-4" style={{ color: '#e2e8f0' }}>
                                    Secured by BOoCArT Payment Simulation. No real money will be deducted.
                                </p>
                            </motion.div>
                        )}

                        {step === 'processing' && (
                            <motion.div
                                key="processing"
                                initial={{ opacity: 0 }}
                                animate={{ opacity: 1 }}
                                className="py-12 flex flex-col items-center justify-center text-center"
                            >
                                <div className="relative w-20 h-20 mb-6">
                                    <div className="absolute inset-0 border-4 border-blue-500/20 rounded-full"></div>
                                    <div className="absolute inset-0 border-4 border-t-blue-500 rounded-full animate-spin"></div>
                                </div>
                                <h3 className="text-xl font-bold text-white mb-2">Simulating Payment...</h3>
                                <p className="text-slate-400 max-w-[200px]">Connecting to simulated bank servers</p>
                            </motion.div>
                        )}

                        {step === 'success' && (
                            <motion.div
                                key="success"
                                initial={{ scale: 0.8, opacity: 0 }}
                                animate={{ scale: 1, opacity: 1 }}
                                className="py-12 flex flex-col items-center justify-center text-center"
                            >
                                <div className="w-20 h-20 bg-green-500/20 text-green-500 rounded-full flex items-center justify-center mb-6">
                                    <HiCheckCircle className="text-6xl" />
                                </div>
                                <h3 className="text-2xl font-bold text-white mb-2">Payment Successful!</h3>
                                <p className="text-slate-400 mb-8">Your transaction has been processed</p>
                                <button
                                    onClick={onClose}
                                    className="w-full py-3 bg-green-600 hover:bg-green-500 text-white font-bold rounded-xl transition-colors"
                                >
                                    Continue
                                </button>
                            </motion.div>
                        )}
                    </AnimatePresence>
                </div>
            </motion.div>
        </div>
    );
}
